# Generated by Django 5.2.1 on 2025-05-27 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0004_alter_customuser_apellido_alter_customuser_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='admitido',
            field=models.BooleanField(default=False),
        ),
    ]
