# Generated by Django 5.2.2 on 2025-06-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0007_alter_customuser_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField()),
                ('nombre_apellido', models.CharField(max_length=100)),
                ('dni', models.IntegerField()),
                ('designacion', models.CharField(max_length=100)),
                ('contacto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DescripcionObjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altura_largo', models.FloatField()),
                ('ancho_diametro_maximo', models.FloatField()),
                ('espesor', models.FloatField()),
                ('otras_alturas', models.FloatField(blank=True, null=True)),
                ('diametro_minimo', models.FloatField(blank=True, null=True)),
                ('otras_medidas', models.CharField(blank=True, max_length=100, null=True)),
                ('forma', models.CharField(max_length=100)),
                ('tecnica', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('adscripcion_cultural_temporal', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoConservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_conservacion', models.CharField(choices=[('malo', 'Malo'), ('regular', 'Regular'), ('bueno', 'Bueno'), ('muy bueno', 'Muy Bueno')], max_length=50)),
                ('estado_estructural', models.CharField(choices=[('entero', 'Entero'), ('fragmentado', 'Fragmentado'), ('completo', 'Completo'), ('incompleto', 'Incompleto'), ('rajadoAgrietado', 'Rajado/Agrietado'), ('restaurado', 'Restaurado'), ('deformado', 'Deformado')], max_length=50)),
                ('estado_superficie', models.CharField(choices=[('sinDeterioro', 'Sin deterioro'), ('suciedadSuperficial', 'Suciedad Superficial'), ('depositosForaneos', 'Depósitos foráneos'), ('desgaste', 'Desgaste'), ('perdida', 'Pérdida'), ('manchas', 'Manchas')], max_length=50)),
                ('intervenciones', models.TextField()),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fotografias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sin_intervencion', models.ImageField(blank=True, null=True, upload_to='fotografias/')),
                ('objeto_intervenido', models.ImageField(blank=True, null=True, upload_to='fotografias/')),
                ('rotulos_detalles', models.ImageField(blank=True, null=True, upload_to='fotografias/')),
                ('otras_fotografias', models.ImageField(blank=True, null=True, upload_to='fotografias/')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroIdentificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_id', models.IntegerField()),
                ('nro_sigla', models.IntegerField()),
                ('sigla_renicoa', models.CharField(blank=True, max_length=50, null=True)),
                ('otros_nro_registro', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_coleccion', models.CharField(max_length=100)),
                ('nombre_descriptivo', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_material', models.CharField(max_length=100)),
                ('anio_coleccion', models.CharField(blank=True, max_length=10, null=True)),
                ('forma_ingreso', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
                ('otros_datos', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroProcedencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=50)),
                ('provincia_region', models.CharField(max_length=50)),
                ('departamento', models.CharField(max_length=50)),
                ('localidad', models.CharField(max_length=50)),
                ('sitio_arqueologico', models.CharField(blank=True, max_length=100, null=True)),
                ('datos_contextuales', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
