# Generated by Django 5.2.2 on 2025-06-06 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0008_datosregistro_descripcionobjeto_estadoconservacion_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DatosRegistro',
        ),
        migrations.DeleteModel(
            name='DescripcionObjeto',
        ),
        migrations.DeleteModel(
            name='EstadoConservacion',
        ),
        migrations.DeleteModel(
            name='Fotografias',
        ),
        migrations.DeleteModel(
            name='RegistroIdentificacion',
        ),
        migrations.DeleteModel(
            name='RegistroProcedencia',
        ),
    ]
